package model;

public enum OrderStatus {
    AGUARDANDO_CONFIRMACAO,
    AGUARDANDO_ACEITE_ENTREGADOR,
    CONFIRMADO,
    PREPARACAO,
    PRONTO,
    EM_ENTREGA,
    AGUARDANDO_CONFIRMACAO_CLIENTE,
    ENTREGUE,
    REJEITADO
}
